modules/weko-schema-ui/weko_schema_ui/views.py
# -*- coding: utf-8 -*-
#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.

"""Blueprint for weko-schema-ui."""

from flask import (
    Blueprint, current_app, redirect, render_template, request, url_for)
from flask_login import login_required

from .permissions import schema_permission
from .schema import delete_schema, delete_schema_cache, schema_list_render

blueprint = Blueprint(
    'weko_schema_ui',
    __name__,
    template_folder='templates',
    static_folder='static',
)


@blueprint.route("/schema", methods=['GET'])
@blueprint.route("/schema/", methods=['GET'])
@login_required
@schema_permission.require(http_exception=403)
def index():
    """Render a basic view."""
    return render_template(
        current_app.config['WEKO_SCHEMA_UI_UPLOAD'],
        record={})


# @blueprint.route("/schema/formats/edit", methods=['GET'])
# @login_required
# @schema_permission.require(http_exception=403)
# def formats():
#     """Render a format edit view."""
#     # record = {"schemas": [{"fmo": {"prefix": "11", "namespace": "22", "schema": "33"}},
#     #           {"fmo": {"prefix": "44", "namespace": "55", "schema": "66"}}]}
# return render_template(current_app.config['WEKO_SCHEMA_UI_FORMAT_EDIT'],
# record={})


@blueprint.route("/schema/list", methods=['GET'])
@blueprint.route("/schema/list/", methods=['GET'])
@login_required
@schema_permission.require(http_exception=403)
def list():
    """Render a schema list view."""
    records = schema_list_render()
    return render_template(
        current_app.config['WEKO_SCHEMA_UI_LIST'],
        records=records)


@blueprint.route("/schema", methods=['POST'])
@blueprint.route("/schema/<pid>", methods=['POST'])
@login_required
@schema_permission.require(http_exception=403)
def delete(pid=None):
    """
    :param pid:
    :return:
    """
    pid = pid or request.values.get('pid')
    schema_name = delete_schema(pid)
    # delete schema cache on redis
    delete_schema_cache(schema_name)

    schema_name = schema_name.replace("_mapping", "")
    # for k, v in current_app.config["RECORDS_UI_EXPORT_FORMATS"].items():
    #     if isinstance(v, dict):
    #         for v1 in v.values():
    #             if v.get(schema_name):
    #                 v.pop(schema_name)
    #                 break
    oaif = current_app.config["OAISERVER_METADATA_FORMATS"]
    if oaif.get(schema_name):
        oaif.pop(schema_name)

    return redirect(url_for(".list"))

modules/weko-schema-ui/weko_schema_ui/templates/weko_schema_ui/base.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    {%- block css %}{%- endblock css %}
    {%- block javascript %}{%- endblock javascript %}
  </head>
  <body>
    {%- block page_body %}{%- endblock page_body %}
  </body>
</html>

modules/weko-schema-ui/weko_schema_ui/templates/weko_schema_ui/list.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{%- extends config.WEKO_SCHEMA_UI_BASE_TEMPLATE %}

{%- block css %}
{% assets "invenio_deposit_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
{{ super() }}
{%- endblock css %}

{%- block javascript %}
{% assets "invenio_deposit_dependencies_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{{ super() }}
{% assets "invenio_deposit_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{% assets "weko_schema_ui_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body_tabs %}
  {% from "weko_theme/macros/edit_tabs_selector.html" import tabs_selector %}
  {{ tabs_selector('schema_management') }}
{%- endblock page_body_tabs%}

{%- block page_body_main %}
<div>
  <div ng-app="myApp" ng-controller="mp" ng-csp>
    <div class="row">
      <div class="body col-sm-12 col-md-9">
        <h4 class="title">{{ _('OAI Schema') }}</h4>
        <a class="btn btn-default" href="{{ url_for('weko_schema_ui.index') }}">
          <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
          {{_('Add Schema')}}
        </a>
        {% if not records %} No Schema .. Please add your greatest schema {% endif %}
        {%- if records -%}
        <table class="table table-bordered table-striped">
          <thead>
          <tr class="">
            <th>{{_('Schema Mapping Name')}}</th>
            <th>{{_('Root Name')}}</th>
            <th>{{_('Operation')}}</th>
          </tr>
          </thead>
          <tbody>
          <form class="form form-inline" action="{{ url_for('.delete')}}" method="POST">
            <div class="form-group">
              {%- for r in records -%}
              {% if r.dis == 'disabled' %}{% set pid = '#' %}{% else %}{% set pid = r.pid %}{% endif %}
              <tr class="">
                <td class="nowrap">{{ r.schema_name }}</td>
                <td class="nowrap">{{ r.root_name }}</td>
                <td class="forcewrap">
                  <span class="pull-left">
                          <a class="btn btn-info" href="{{url_for('weko_itemtypes_ui.mapping_index')}}">
                            <i class="fa fa-hand-o-right"></i> {{_("Go Mapping")}}</a>
                          <button class="btn btn-danger" name="pid" type="submit" value="{{pid}}" {{r.dis}}><i
                            class="fa fa fa-cut"></i> {{_("Delete")}}</a></button>
                  </span>
                </td>
              </tr>
              {%- endfor -%}
            </div>
          </form>
          </tbody>
        </table>
        {%- endif %}
      </div>
    </div>
  </div>
</div>
{%- endblock page_body_main %}

modules/weko-schema-ui/weko_schema_ui/templates/weko_schema_ui/upload.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{%- extends config.WEKO_SCHEMA_UI_BASE_TEMPLATE %}

{%- block css %}
  {% assets "invenio_deposit_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
  {{ super() }}
{%- endblock css %}

{%- block javascript %}
  {% assets "invenio_deposit_dependencies_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
  {{ super() }}
  {% assets "invenio_deposit_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
  {% assets "weko_schema_ui_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body_tabs %}
  {% from "weko_theme/macros/edit_tabs_selector.html" import tabs_selector %}
  {{ tabs_selector('schema_management') }}
{%- endblock page_body_tabs%}

{%- block page_body_main %}
  <div>
    <div class="row">
      <div class="col-md-12">
        <div id="invenio-records">
          <invenio-files-uploader
            method="PUT"
            endpoint="{{ config.WEKO_SCHEMA_UI_FILES_API }}"
            {% if pid %}
              action="{{ config.WEKO_SCHEMA_UI_RECORD_API|format(pid_value=pid.pid_value) }}"
            {% else %}
              initialization="{{ config.WEKO_SCHEMA_UI_SEARCH_API }}"
            {% endif %}
            extra-params='{"headers":{"Content-Type": "application/json"}}'
          >
            <invenio-records
              initialization="{{ config.WEKO_SCHEMA_UI_SEARCH_API }}"
              response-params='{{ config.WEKO_SCHEMA_UI_RESPONSE_MESSAGES | tojson }}'
              extra-params='{"headers":{"Content-Type": "application/json"}}'
              form="{{ url_for('static', filename=config.WEKO_SCHEMA_UI_DEFAULT_SCHEMAFORM) }}"
              schema="{{ url_for('static', filename=config.WEKO_SCHEMA_UI_FORM_JSONSCHEMA) }}"
              record='{{record}}'>
              <invenio-records-loading
                template="{{ url_for('static', filename='node_modules/invenio-records-js/dist/templates/loading.html') }}">
              </invenio-records-loading>
              <invenio-records-alert
                template="{{ url_for('static', filename='node_modules/invenio-records-js/dist/templates/alert.html') }}">
              </invenio-records-alert>
              <div ng-hide="false">
                <div ng-show="true">
                  <ul class="list-inline text-right">
                    <li><button ng-disabled="recordsVM.invenioRecordsLoading" class="btn btn-default" ng-click="recordsVM.actionHandler(['self', 'POST'])">{{_('Transmission')}}</button></li>
                    <li><button ng-disabled="recordsVM.invenioRecordsLoading" ng-hide="!recordsVM.invenioRecordsEndpoints.initialization" class="btn btn-danger" ng-click="recordsVM.actionHandler(['self', 'DELETE'])">{{_('Delete')}}</button></li>
                  </ul>
                </div>
              </div>
              <invenio-files-upload-zone
                template="{{ url_for('static', filename='node_modules/invenio-files-js/dist/templates/upload.html') }}">
              </invenio-files-upload-zone>
              <invenio-files-list
                template="{{ url_for('static', filename='node_modules/invenio-files-js/dist/templates/list.html') }}"
              ></invenio-files-list>
              <invenio-records-form
                form-templates='{{ config.DEPOSIT_FORM_TEMPLATES | tojson }}'
                form-templates-base="{{ url_for('static', filename=config.DEPOSIT_FORM_TEMPLATES_BASE) }}"
                template="{{ url_for('static', filename=config.DEPOSIT_UI_JSTEMPLATE_FORM) }}">
              </invenio-records-form>
              <div ng-hide="false">
                <div ng-show="true">
                  <ul class="list-inline text-right">
                    <li><button ng-disabled="recordsVM.invenioRecordsLoading" class="btn btn-default" ng-click="recordsVM.actionHandler(['self', 'POST'])">{{_('Transmission')}}</button></li>
                    <li><button ng-disabled="recordsVM.invenioRecordsLoading" ng-hide="!recordsVM.invenioRecordsEndpoints.initialization" class="btn btn-danger" ng-click="recordsVM.actionHandler(['self', 'DELETE'])">{{_('Delete')}}</button></li>
                  </ul>
                </div>
              </div>
            </invenio-records>
          </invenio-files-uploader>
        </div>
      </div>
    </div>
  </div>
{%- endblock page_body_main %}