modules/weko-workflow/weko_workflow/views.py
# -*- coding: utf-8 -*-
#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.

"""Blueprint for weko-workflow."""


from functools import wraps
from flask import Blueprint, abort, current_app, jsonify, render_template, \
    request, session, url_for
from flask_babelex import gettext as _
from flask_login import current_user, login_required
from invenio_accounts.models import Role, userrole
from invenio_db import db
from invenio_pidstore.models import PersistentIdentifier
from invenio_pidstore.resolver import Resolver
from sqlalchemy.orm.exc import NoResultFound
from werkzeug.utils import import_string
from weko_records.api import ItemsMetadata

from .api import Action, Flow, WorkActivity, WorkActivityHistory, WorkFlow, UpdateItem, GetCommunity
from .models import ActionStatusPolicy, ActivityStatusPolicy

blueprint = Blueprint(
    'weko_workflow',
    __name__,
    template_folder='templates',
    static_folder='static',
    url_prefix='/workflow'
)


@blueprint.route('/')
@login_required
def index():
    """Render a basic view."""
    activity = WorkActivity()
    getargs = request.args
    ctx = {'community': None}
    community_id = ""
    if 'community' in getargs:
        current_app.logger.debug(request.args.get('community'))
        activities = activity.get_activity_list(request.args.get('community'))
        comm = GetCommunity.get_community_by_id(request.args.get('community'))
        ctx = {'community': comm}
        community_id =comm.id
    else:
        activities = activity.get_activity_list()
    return render_template(
        'weko_workflow/activity_list.html',
        activities=activities, community_id=community_id, **ctx
    )

@blueprint.route('/iframe/success', methods=['GET'])
def iframe_success():
    """Renders an item register view.

    :return: The rendered template.
    """
    return render_template('weko_workflow/item_login_success.html')


@blueprint.route('/activity/new', methods=['GET'])
@login_required
def new_activity():
    workflow = WorkFlow()
    workflows = workflow.get_workflow_list()
    getargs = request.args
    ctx = {'community': None}
    community_id=""
    if 'community' in getargs:
        comm = GetCommunity.get_community_by_id(request.args.get('community'))
        ctx = {'community': comm}
        community_id = comm.id
    return render_template(
        'weko_workflow/workflow_list.html',
        workflows=workflows, community_id =community_id, **ctx
    )


@blueprint.route('/activity/init', methods=['POST'])
@login_required
def init_activity():
    post_activity = request.get_json()
    activity = WorkActivity()
    getargs = request.args
    if 'community' in getargs:
        rtn = activity.init_activity(post_activity, request.args.get('community'))
    else:
        rtn = activity.init_activity(post_activity)
    if rtn is None:
        return jsonify(code=-1, msg='error')
    if 'community' in getargs:
        comm = GetCommunity.get_community_by_id(request.args.get('community'))
        return jsonify(code=0, msg='success',
                       data={'redirect': url_for(
                           'weko_workflow.display_activity',
                           activity_id=rtn.activity_id, community=comm.id)})
    return jsonify(code=0, msg='success',
                   data={'redirect': url_for(
                       'weko_workflow.display_activity',
                       activity_id=rtn.activity_id)})


@blueprint.route('/activity/list', methods=['GET'])
@login_required
def list_activity():
    activity = WorkActivity()
    activities = activity.get_activity_list()
    return render_template(
        'weko_workflow/activity_list.html',
        activities=activities
    )


@blueprint.route('/activity/detail/<string:activity_id>', methods=['GET'])
@login_required
def display_activity(activity_id=0):
    activity = WorkActivity()
    activity_detail = activity.get_activity_detail(activity_id)
    item = None
    if activity_detail is not None and activity_detail.item_id is not None:
        try:
            item = ItemsMetadata.get_record(id_=activity_detail.item_id)
        except NoResultFound as ex:
            current_app.logger.exception(str(ex))
            item = None
    steps = activity.get_activity_steps(activity_id)
    history = WorkActivityHistory()
    histories = history.get_activity_history_list(activity_id)
    workflow = WorkFlow()
    workflow_detail = workflow.get_workflow_by_id(
        activity_detail.workflow_id)
    if ActivityStatusPolicy.ACTIVITY_FINALLY != activity_detail.activity_status:
        activity_detail.activity_status_str = \
            request.args.get('status', 'ToDo')
    else:
        activity_detail.activity_status_str = _('End')
    cur_action = activity_detail.action
    action_endpoint = cur_action.action_endpoint
    action_id = cur_action.id
    temporary_comment = activity.get_activity_action_comment(
        activity_id=activity_id, action_id=action_id)
    if temporary_comment:
        temporary_comment = temporary_comment.action_comment
    cur_step = action_endpoint
    step_item_login_url = None
    approval_record = []
    pid = None
    if 'item_login' == action_endpoint or 'file_upload' == action_endpoint:
        activity_session = dict(
            activity_id=activity_id,
            action_id=activity_detail.action_id,
            action_version=cur_action.action_version,
            action_status=ActionStatusPolicy.ACTION_DOING,
            commond=''
        )
        session['activity_info'] = activity_session
        step_item_login_url = url_for(
            'weko_items_ui.iframe_index',
            item_type_id=workflow_detail.itemtype_id)
        if item:
            pid_identifier = PersistentIdentifier.get_by_object(
                pid_type='depid', object_type='rec', object_uuid=item.id)
            step_item_login_url = url_for(
                'invenio_deposit_ui.iframe_depid',
                pid_value=pid_identifier.pid_value)
    # if 'approval' == action_endpoint:
    if item:
        pid_identifier = PersistentIdentifier.get_by_object(
            pid_type='depid', object_type='rec', object_uuid=item.id)
        record_class = import_string('weko_deposit.api:WekoRecord')
        resolver = Resolver(pid_type='recid', object_type='rec',
                            getter=record_class.get_record)
        pid, approval_record = resolver.resolve(pid_identifier.pid_value)

    res_check = check_authority_action(activity_id,action_id)

    getargs = request.args
    ctx = {'community': None}
    community_id = ""
    if 'community' in getargs:
        comm = GetCommunity.get_community_by_id(request.args.get('community'))
        community_id=request.args.get('community')
        ctx = {'community': comm}
        community_id = comm.id
    return render_template(
        'weko_workflow/activity_detail.html',
        activity=activity_detail,
        item=item,
        steps=steps,
        action_id=action_id,
        cur_step=cur_step,
        temporary_comment=temporary_comment,
        record=approval_record,
        step_item_login_url=step_item_login_url,
        histories=histories,
        res_check=res_check,
        pid=pid,
        community_id=community_id,
        **ctx
    )


def check_authority(func):
    @wraps(func)
    def decorated_function(*args, **kwargs):
        work = WorkActivity()
        roles, users = work.get_activity_action_role(
            activity_id=kwargs.get('activity_id'),
            action_id=kwargs.get('action_id'))
        cur_user = current_user.get_id()
        cur_role = db.session.query(Role).join(userrole).filter_by(
            user_id=cur_user).all()
        if users['deny'] and int(cur_user) in users['deny']:
            return jsonify(code=403, msg=_('Authorization required'))
        if users['allow'] and int(cur_user) not in users['allow']:
            return jsonify(code=403, msg=_('Authorization required'))
        for role in cur_role:
            if roles['deny'] and role.id in roles['deny']:
                return jsonify(code=403, msg=_('Authorization required'))
            if roles['allow'] and role.id not in roles['allow']:
                return jsonify(code=403, msg=_('Authorization required'))
        return func(*args, **kwargs)
    return decorated_function


def check_authority_action(activity_id='0', action_id=0):
    work = WorkActivity()
    roles, users = work.get_activity_action_role(activity_id, action_id)
    cur_user = current_user.get_id()
    cur_role = db.session.query(Role).join(userrole).filter_by(
        user_id=cur_user).all()
    if users['deny'] and int(cur_user) in users['deny']:
        return 1
    if users['allow'] and int(cur_user) not in users['allow']:
        return 1
    for role in cur_role:
        if roles['deny'] and role.id in roles['deny']:
            return 1
        if roles['allow'] and role.id not in roles['allow']:
            return 1
    return 0


@blueprint.route(
    '/activity/action/<string:activity_id>/<int:action_id>',
    methods=['POST'])
@login_required
@check_authority
def next_action(activity_id='0', action_id=0):
    post_json = request.get_json()
    activity = dict(
        activity_id=activity_id,
        action_id=action_id,

modules/weko-workflow/weko_workflow/templates/weko_workflow/activity_detail.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{%- extends config.WEKO_WORKFLOW_BASE_TEMPLATE %}
{%- from "invenio_communities/macros.html" import community_header, community_footer %}

{%- block css %}
{{ super() }}
{% assets "workflow_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
{%- endblock css %}

{%- block javascript %}
{{ super() }}
{% assets "workflow_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body_tabs %}
  {% from "weko_theme/macros/tabs_selector.html" import tabs_selector %}
  {{ tabs_selector('flow', community_id) }}
{%- endblock page_body_tabs %}

{%- block page_header %}
{%-if not community %}
{{ super() }}
{%- endif%}
{%- endblock page_header %}

{%- block page_footer %}
{%-if not community%}
{{ super() }}
{%- endif%}
{%- endblock page_footer %}

{%- block page_body_main %}
<div class="row">
  {%-if community%}
  <div id="community_id" class="hide">{{community.id}}</div>
  {%-else %}
  <div id="community_id" class="hide"></div>
  {%-endif %}
  <div class="col-sm-12">
    <div id="workFlow" class="panel-group">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-3">
              <div class="form-horizontal">
                <div class="form-group">
                  <label class="col-sm-4 control-label">{{_('Flow')}}</label>
                  <div class="col-sm-8">
                    <p class="form-control-static">{{activity.flow_define.flow_name}}</p>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-4 control-label">{{_('Activity')}}</label>
                  <div class="col-sm-8">
                    <p class="form-control-static">{{activity.activity_id}}</p>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-4 control-label">{{_('Status')}}</label>
                  <div class="col-sm-8">
                    <p class="form-control-static">{{activity.activity_status_str}}</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-2">
              <div class="form-horizontal">
                <div class="form-group">
                  <label class="col-sm-4 control-label">{{_('Created')}}</label>
                  <div class="col-sm-8">
                    <p class="form-control-static">{{activity.activity_start.date()}}</p>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-4 control-label">{{_('Creater')}}</label>
                  <div class="col-sm-8">
                    <p class="form-control-static">{{activity.login_user if activity.login_user else activity.activity_login_user}}</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-2">
              <div class="form-horizontal">
                <div class="form-group">
                  <label class="col-sm-4 control-label">{{_('Updated')}}</label>
                  <div class="col-sm-8">
                    <p class="form-control-static">{{activity.updated.date()}}</p>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-4 control-label">{{_('Updater')}}</label>
                  <div class="col-sm-8">
                    <p class="form-control-static">{{activity.update_user if activity.update_user else activity.activity_update_user}}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-3">
              <div class="form-horizontal">
                <div class="form-group">
                  <label class="col-sm-4 control-label">{{_('Item')}}</label>
                  <div class="col-sm-8">
                    <p class="form-control-static">
                    <a href="#" id="lnk_item_detail">{{item.get('title_ja') if item}}</a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <span class="indent">{{_('Step')}}</span>
        <div class="panel-body">
          <div class="row">
            {%- for step in steps %}
            <div class="col-sm-2">
              <div class="row">
                <div class="col-sm-9">
                  <ul class="list-group">
                    <li class="list-group-item break-word {% if cur_step == step.ActionEndpoint %} style_li {% endif %}">
                      <span class="action-name {% if cur_step == step.ActionEndpoint %} cur_step style_a {% endif %}"
                         data-action-version="{{step.ActionVersion}}"
                         data-next-uri="{{url_for('weko_workflow.next_action', activity_id=step.ActivityId, action_id=step.ActionId)}}">{{step.ActionName}}</span></li>
                    <li class="list-group-item break-word {% if cur_step == step.ActionEndpoint %} style_li {% endif %}">
                      <span class="action-name {% if cur_step == step.ActionEndpoint %} style_a {% endif %}">{{step.Author}}</span></li>
                    <li class="list-group-item {% if cur_step == step.ActionEndpoint %} style_li style_a {% endif %}">{{_(step.Status)}}</li>
                  </ul>
                </div>
                {%- if 'end_action' != step.ActionEndpoint %}
                <div class="col-sm-3 pull-right">
                  <span class="glyphicon glyphicon-arrow-right rightFoward_font" aria-hidden="true"></span>
                </div>
                {%- endif %}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      {%- if 'F' != activity.activity_status %}
      <div class="hide" id="hide-res-check">{{res_check}}</div>
      <div class="panel panel-default">
        {%- if 0 != res_check %}
          <div class="panel-body" id="step_page_permission">
            {% include 'weko_workflow/permission_required.html' %}
          </div>
        {%- else %}
          <div class="panel-body" id="step_page">
            <div class="hide" id="hide-actionId">{{action_id}}</div>
            {%- if step_item_login_url %}
              <iframe id="step_item_login" name="step_item_login" frameborder="0" width="100%" height="700px" src="{{step_item_login_url}}"></iframe>
            {%- else %}
              {%- if 'approval' == cur_step %}
                {% include 'weko_workflow/record_detail.html' %}
              {% endif %}
              <div class="form-group">
                <label class="sr-only" for="input-comment">{{_('Comment')}}</label>
                <div class="input-group">
                  <div class="input-group-addon">{{_('Comment')}}</div>
                  <textarea class="form-control" rows="5" id="input-comment" placeholder="">{{temporary_comment if temporary_comment else ''}}</textarea>
                </div>
              </div>
              {%- if 'approval_request' == cur_step %}
                <button type="button" class="btn btn-default" id="btn-approval-req">{{_('Approval Request')}}</button>
                <button type="button" class="btn btn-default" id="btn-finish">{{_('Run')}}</button>
              {%- endif %}
              {%- if 'approval' == cur_step %}
                <button type="button" class="btn btn-default" id="btn-approval">{{_('Approval')}}</button>
                <button type="button" class="btn btn-default" id="btn-reject">{{_('Reject')}}</button>
                <button type="button" class="btn btn-default" id="btn-return">{{_('Return')}}</button>
                <button type="button" class="btn btn-default" id="btn-draft">{{_('Save')}}</button>
              {%- endif %}
              {%- if 'double_check' == cur_step %}
                <button type="button" class="btn btn-default" id="btn-draft">{{_('Save')}}</button>
                <button type="button" class="btn btn-default" id="btn-finish">{{_('Run')}}</button>
              {%- endif %}
              {%- if 'end_action' == cur_step %}
                <button type="button" class="btn btn-default" id="btn-draft">{{_('Save')}}</button>
                <button type="button" class="btn btn-default" id="btn-finish">{{_('Run')}}</button>
              {%- endif %}
            {%- endif %}
          </div>
        {%- endif %}
      </div>
      {%- endif %}
      <div class="panel panel-default">
        <span class="indent">{{_('History')}}</span>
        <div class="panel-body">
          <table class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>{{_('Action')}}</th>
            <th>{{_('Updated')}}</th>
            <th>{{_('Updater')}}</th>
            <th>{{_('Result')}}</th>
            <th>{{_('Comment')}}</th>
          </tr>
          </thead>
          <tbody>
          {%- if histories %}
          {%- for history in histories %}
          <tr>
            <td>{{history.ActionName[0]}}</td>
            <td>{{history.action_date.strftime('%Y-%m-%d %H:%M')}}</td>
            <td>{{history.user.email}}</td>
            <td>{{_(history.StatusDesc)}}</td>
            <td>{{history.CommentDesc}}</td>
          </tr>
          {% endfor %}
          {% else %}
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          {% endif %}
          </tbody>
        </table>
        </div>
      </div>
    </div>
    {%-if community%}
    <a class="btn btn-default pull-right" href="{{url_for('weko_workflow.index',community=community.id)}}">{{_('Back')}}</a>
    {%-else%}
    <a class="btn btn-default pull-right" href="{{url_for('weko_workflow.index')}}">{{_('Back')}}</a>
    {%-endif%}
  </div>
</div>
{%- endblock page_body_main %}
{%- block page_body %}
{%-if community %}
<div class="communities">
<div id="community-id" name="community-id" hidden>{{ community.id }}</div>
{{ community_header(community, subtitle='') }}
{%- endif%}
{{ super() }}
<div ng-controller="AuthorModalCtrl" class="modal fade" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog modelWidth" role="document">
    <div class="modal-content">
      <div class="modal-body">
        {% include 'weko_workflow/record_detail.html' %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="btnModalClose" data-dismiss="modal">{{_('Close')}}</button>
      </div>
    </div>
  </div>
</div>
{%-if community %}
{{ community_footer(community, link=False, subtitle='') }}
</div>
<div class="communities">
</div>
{%- endif%}
{%- endblock page_body %}

modules/weko-workflow/weko_workflow/templates/weko_workflow/activity_list.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{%- extends config.WEKO_WORKFLOW_BASE_TEMPLATE %}
{%- from "invenio_communities/macros.html" import community_header, community_footer %}

{%- block css %}
  {{ super() }}
{%- endblock css %}

{%- block javascript %}
  {{ super() }}
  {%- assets "workflow_activity_list_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body_tabs %}
  {% from "weko_theme/macros/tabs_selector.html" import tabs_selector %}
  {{ tabs_selector('flow',community_id) }}
{%- endblock page_body_tabs %}

{%- block page_header %}
{%-if not community %}
{{ super() }}
{%- endif%}
{%- endblock page_header %}

{%- block page_footer %}
{%-if not community%}
{{ super() }}
{%- endif%}
{%- endblock page_footer %}

{% block page_body %}
{%-if not community %}
{{super()}}
{%- else%}
<div class="communities">
<div id="community-id" name="community-id" hidden>{{ community.id }}</div>
{{ community_header(community, subtitle='') }}
{{super()}}
{{ community_footer(community, link=False, subtitle='') }}
</div>
<div class="communities">
</div>
{%- endif%}
{% endblock page_body %}


{%- block page_body_main %}
<div role="navigation">
  <ul class="nav nav-tabs">
    <li role="presentation" class="active activity_li">
      <a href="javascript:void();" class="activity_tab" data-show-tab="todo">{{_('ToDo')}}</a></li>
    <li role="presentation" class="activity_li">
      <a href="javascript:void();" class="activity_tab" data-show-tab="wait">{{_('Wait')}}</a></li>
    <li role="presentation" class="activity_li">
      <a href="javascript:void();" class="activity_tab" data-show-tab="all">{{_('All')}}</a></li>
  </ul>
</div>
<div class="row">
  <div class="col-sm-12">
    <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>{{ _('No.') }}</th>
        <th>{{ _('Updated') }}</th>
        <th>{{ _('Activity') }}</th>
        <th>{{_('Item')}}</th>
        <th>{{_('WorkFlow')}}</th>
        <th>{{_('Action')}}</th>
        <th>{{_('Status')}}</th>
        <th>{{_('User')}}</th>
      </tr>
    </thead>
    <tbody>
    {%- for activity in activities %}
      <tr class="hide tb-all {%- if 'ToDo' == activity.type %} tb-todo {%- elif 'Wait' == activity.type %} tb-wait {%- endif %}">
        <th scope="row">{{loop.index}}</th>
        <td>{{activity.updated.date()}}</td>
        {%-if community%}
        <td><a href="{{url_for('weko_workflow.display_activity', activity_id=activity.activity_id, status=activity.type, community=community.id)}}">{{activity.activity_id}}</a></td>
        {%-else%}
        <td><a href="{{url_for('weko_workflow.display_activity', activity_id=activity.activity_id, status=activity.type)}}">{{activity.activity_id}}</a></td>
        {%- endif%}
        <td>{{activity.ItemName}}</td>
        <td>{{activity.workflow.flows_name}}</td>
        <td>{{activity.action.action_name}}</td>
        <td>{{_(activity.StatusDesc)}}</td>
        <td>{{activity.User.email}}</td>
      </tr>
    {%- endfor %}
    </tbody>
    </table>
    {%-if community%}
      <a class="btn btn-default pull-right" href="{{url_for('weko_workflow.new_activity', community=community.id)}}">{{_('New Activity')}}</a>
    {%-else%}
      <a class="btn btn-default pull-right" href="{{url_for('weko_workflow.new_activity')}}">{{_('New Activity')}}</a>
    {%- endif%}

  </div>
</div>
{%- endblock page_body_main %}

modules/weko-workflow/weko_workflow/templates/weko_workflow/workflow_list.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{%- extends config.WEKO_WORKFLOW_BASE_TEMPLATE %}
{%- from "invenio_communities/macros.html" import community_header, community_footer %}

{%- block css %}
{{ super() }}
{%- endblock css %}

{%- block javascript %}
{{ super() }}
{% assets "workflow_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body_tabs %}
  {% from "weko_theme/macros/tabs_selector.html" import tabs_selector %}
  {{ tabs_selector('flow', community_id) }}
{%- endblock page_body_tabs %}

{%- block page_header %}
{%-if not community %}
{{ super() }}
{%- endif%}
{%- endblock page_header %}

{%- block page_footer %}
{%-if not community%}
{{ super() }}
{%- endif%}
{%- endblock page_footer %}

{% block page_body %}
{%-if not community %}
{{super()}}
{%- else%}
<div class="communities">
<div id="community-id" name="community-id" hidden>{{ community.id }}</div>
{{ community_header(community, subtitle='') }}
{{super()}}
{{ community_footer(community, link=False, subtitle='') }}
</div>
<div class="communities">
</div>
{%- endif%}
{% endblock page_body %}


{%- block page_body_main %}
<div class="row">
  <div class="col-sm-12">
    <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>{{_('No.')}}</th>
        <th>{{_('WorkFlow')}}</th>
        <th>{{_('Begin')}}</th>
        <th>{{_('ItemType')}}</th>
        <th>{{_('Flow')}}</th>
        <th class="hide">{{_('Next Flow')}}</th>
      </tr>
    </thead>
    <tbody>
    {%- for workflow in workflows %}
      <tr>
        <th scope="row">{{loop.index}}</th>
        <td>{{workflow.flows_name}}</td>
        {%-if community%}
        <td><a href="#" class="btn btn-primary btn-begin" id="btn-begin-{{workflow.id}}" data-workflow-id="{{workflow.id}}" data-community="{{community.id}}">{{_('Begin')}}</a></td>
        {%- else%}
        <td><a href="#" class="btn btn-primary btn-begin" id="btn-begin-{{workflow.id}}" data-workflow-id="{{workflow.id}}" data-community="">{{_('Begin')}}</a></td>
        {%- endif%}
        <td><span id="item_type_{{workflow.id}}" data-itemtype-id="{{workflow.itemtype_id}}">{{_(workflow.itemtype.item_type_name.name)}}</span></td>
        <td><span id="flow_{{workflow.id}}" data-flow-id="{{workflow.flow_id}}">{{_(workflow.flow_define.flow_name)}}</span></td>
        <td class="hide"> </td>
      </tr>
    {%- endfor %}
    </tbody>
  </table>
  <div class="hide" id="post_uri">{{url_for('weko_workflow.init_activity')}}</div>
  <a class="btn btn-default pull-right" href="{{url_for('weko_workflow.index')}}">{{_('Back')}}</a>
  </div>
</div>
{%- endblock page_body_main %}