modules/weko-index-tree/weko_index_tree/views.py
# -*- coding: utf-8 -*-
#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.

"""Blueprint for weko-index-tree."""


import os

from flask import Blueprint, abort, current_app, \
    flash, jsonify, render_template, request, url_for,session
from flask_babelex import gettext as _
from flask_login import login_required

from .permissions import index_tree_permission

blueprint = Blueprint(
    'weko_index_tree',
    __name__,
    url_prefix='/indextree',
    template_folder='templates',
    static_folder='static',
)


@blueprint.route('/')
@login_required
@index_tree_permission.require(http_exception=403)
def index():
    """Render the index tree edit page."""

    return render_template(
        current_app.config['WEKO_INDEX_TREE_INDEX_TEMPLATE'],
        get_tree_json=current_app.config['WEKO_INDEX_TREE_LIST_API'],
        upt_tree_json='',
        mod_tree_detail=current_app.config['WEKO_INDEX_TREE_API']
    )


@blueprint.route('/upload', methods=['GET', 'POST'])
def upload_image():

    if 'uploadFile' not in request.files:
        current_app.logger.debug('No file part')
        flash(_('No file part'))
        return abort(400)
    fp = request.files['uploadFile']
    if '' == fp.filename:
        current_app.logger.debug('No selected file')
        flash(_('No selected file'))
        return abort(400)

    filename = os.path.join(
        current_app.static_folder, 'indextree', fp.filename)
    file_uri = url_for('static', filename='indextree/'+fp.filename)
    fp.save(filename)
    return jsonify({'code': 0, 'msg': 'file upload success', 'data': {'path': file_uri}})

modules/weko-index-tree/weko_index_tree/templates/weko_index_tree/base.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    {%- block page_body %}{%- endblock page_body %}
    <form id="logofileupload" class="form-inline" action={{url_for('weko_index_tree.upload_image')}} method="post" enctype="multipart/form-data">
      <div class="row fileupload-buttonbar">
        <div class="col-sm-10">
          <span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
            <span>{{_('Add Logo file...')}}</span>
            <input type="file" id="uploadFile" name="uploadFile">
          </span>
          <button type="submit" class="btn btn-primary start">
            <i class="glyphicon glyphicon-upload"></i>
            <span>{{_('Start upload')}}</span>
          </button>
        </div>
      </div>
    </form>
  </body>
</html>

modules/weko-index-tree/weko_index_tree/templates/weko_index_tree/index.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

{%- extends config.WEKO_INDEX_TREE_BASE_TEMPLATE %}

{%- block css %}
  {% assets "weko_items_ui_indextree_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
  {% assets "weko_index_tree_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
  {{ super() }}
{%- endblock css %}

{%- block javascript %}
  {% assets "weko_index_tree_view" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
  {{ super() }}
  {% assets "weko_index_tree_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body_tabs %}
  {% from "weko_theme/macros/edit_tabs_selector.html" import tabs_selector %}
  {{ tabs_selector('edit_tree') }}
{%- endblock page_body_tabs%}

{%- block page_body_main %}
<div class="row">
  <div class="hide" id="get_tree_json">{{ get_tree_json }}</div>
  <div class="hide" id="upt_tree_json">{{ upt_tree_json }}</div>
  <div class="hide" id="mod_tree_detail">{{ mod_tree_detail }}</div>
  <app-root-tree-hensyu></app-root-tree-hensyu>
</div>
{%- endblock page_body_main %}

modules/weko-index-tree/weko_index_tree/templates/weko_index_tree/tree_edit.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}
{%- extends config.WEKO_INDEX_TREE_BASE_TEMPLATE %}

{%- block css %}
  {% assets "weko_index_tree_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
  {{ super() }}
{%- endblock css %}

{%- block javascript %}
  {{ super() }}
  {% assets "weko_index_tree_view" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
  {% assets "weko_index_tree_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body_tabs %}
  {% from "weko_theme/macros/edit_tabs_selector.html" import tabs_selector %}
  {{ tabs_selector('edit_tree') }}
{%- endblock page_body_tabs%}

{%- block page_body_main %}
<div class="row">
  <div class="col-sm-2 col-md-2 col-lg-2">
    <div id="index_tree"></div>
  </div>
  <div class="col-sm-10el-default">
      <div class="panel-he col-md-10 col-lg-10">
    <div class="panel panading">
        <h3 class="panel-title">{{_('Index Tree')}}</h3>
      </div>
      <div class="panel-body">
        <textarea class="form-control" rows="30" id="index-tree">{{ index_tree }}</textarea>
      </div>
      <div class="panel-footer">
        <button id="index-tree-submit" class="btn btn-default">{{_('sending')}}</button>
      </div>
    </div>
  </div>
</div>
{%- endblock page_body_main %}
{%- block page_body %}
{{ super() }}
<!-- modal start -->
<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{_('Result')}}</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{_('Close')}}</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{%- endblock page_body %}